package it.polimi.ingsw.model;

public enum Response {

    //Response for match beginning

    CHALLENGERCHOICE,CHALLENGERCHOICEERROR,CHALLENGERCHOICEDONE,CARDCHOICE,CARDCHOICEERROR,CARDCHOICEDONE,PLACEWORKERS,PLACEWORKERSERROR,PLACEWORKERSDONE,STARTTURN,STARTURNERROR,

    //Response for game logic
    NEWMOVE,MOVED,BUILD,NOTMOVED,NOTBUILD,NOTBUILDPLACE,NEWBUILD,ASSIGNCONSTRAINT,WIN, BUILDWIN, NOTWIN,NOTBUILDWIN,TOMOVE,BUILDBEFORE,BUILDEDBEFORE,LOOSE,

    //Error status in game logic
    MOVEWINMISMATCH,BUILDWINMISMATCH,STATUSERROR,

    ENDTURN,ASSIGNEDCONSTRAINT,


    //Response for game config

    PLAYERADDED,NICKUSED,GAMESTARTED,REMOVEDPLAYER

}
