package it.polimi.ingsw.network.message;

public enum MessageType {
    //network messages
    START,NICK,CONFIG,WAITPLAYER,NUMBERPLAYER,GAMESTART,DISCONNECTION,NOTYOURTURN,
    //gamecontroller messages
    SELECTPOWERSFORMATCH, SELECTPOWER,STARTTURN, ENDTURN,POWERCHOICE,PLACEWORKERS,CHALLENGERCHOICE,CHOOSECARD,
    //roundcontroller messages
    WORKERCHOICE,MOVEWORKER, BUILDWORKER, WIN,NONPERMCONSTRAINT,PERMCONSTRAINT,

    PING

}
